#ifndef _CUPS_CUPS_H_
# define _CUPS_CUPS_H_

# include <stdint.h>

# ifdef __cplusplus
extern "C" {
# endif

typedef struct http_s http_t;
typedef struct cups_s cups_t;

enum {
    CUPS_HTTP_DEFAULT = 0,
    IPP_PORT = 631
};

typedef enum {
    IPP_OK = 0,
    IPP_OK_SUBST = 1,
    IPP_REDIRECTION_OTHER_SITE = 2,
    IPP_BAD_REQUEST = 0x0400,
    IPP_FORBIDDEN = 0x0401,
    IPP_NOT_AUTHENTICATED = 0x0402,
    IPP_NOT_AUTHORIZED = 0x0403,
    IPP_NOT_POSSIBLE = 0x0404,
    IPP_TIMEOUT = 0x0405,
    IPP_NOT_FOUND = 0x0406,
    IPP_GONE = 0x0407,
    IPP_REQUEST_ENTITY_TOO_LARGE = 0x0408,
    IPP_REQUEST_VALUE_TOO_LARGE = 0x0409,
    IPP_DOCUMENT_FORMAT_ERROR = 0x040A,
    IPP_ATTRIBUTES_OR_VALUES_NOT_SUPPORTED = 0x040B,
    IPP_URI_SCHEME_NOT_SUPPORTED = 0x040C,
    IPP_CHARSET_NOT_SUPPORTED = 0x040D,
    IPP_CONFLICT = 0x040E,
    IPP_COMPRESSION_NOT_SUPPORTED = 0x040F,
    IPP_COMPRESSION_ERROR = 0x0410,
    IPP_DOCUMENT_FORMAT_ERROR2 = 0x0411,
    IPP_DOCUMENT_ACCESS_ERROR = 0x0412,
    IPP_ATTRIBUTE_NOT_SUPPORTED = 0x0413,
    IPP_MULTIPLE_JOBS_NOT_SUPPORTED = 0x0414,
    IPP_PRINTER_IS_ACCEPTING_JOBS = 0x0500,
    IPP_SERVICE_UNAVAILABLE = 0x0502,
    IPP_INTERNAL_ERROR = 0x0500,
    IPP_VERSION_NOT_SUPPORTED = 0x0503
} ipp_status_t;

typedef enum {
    IPP_TAG_ZERO = 0x00,
    IPP_TAG_OPERATION = 0x01,
    IPP_TAG_JOB = 0x02,
    IPP_TAG_END = 0x03,
    IPP_TAG_PRINTER = 0x04,
    IPP_TAG_UNSUPPORTED_GROUP = 0x05,
    IPP_TAG_SUBSCRIPTION = 0x06,
    IPP_TAG_EVENT_NOTIFICATION = 0x07,
    IPP_TAG_RESOURCE = 0x08,
    IPP_TAG_DOCUMENT = 0x09,
    IPP_TAG_UNSUPPORTED_VALUE = 0x10,
    IPP_TAG_DEFAULT = 0x11,
    IPP_TAG_UNKNOWN = 0x12,
    IPP_TAG_NOVALUE = 0x13,
    IPP_TAG_NOTSETTABLE = 0x15,
    IPP_TAG_DELETEATTR = 0x16,
    IPP_TAG_ADMINDEFINE = 0x17,
    IPP_TAG_INTEGER = 0x21,
    IPP_TAG_BOOLEAN = 0x22,
    IPP_TAG_ENUM = 0x23,
    IPP_TAG_STRING = 0x30,
    IPP_TAG_DATE = 0x31,
    IPP_TAG_RESOLUTION = 0x32,
    IPP_TAG_RANGE = 0x33,
    IPP_TAG_BEGIN_COLLECTION = 0x34,
    IPP_TAG_TEXTLANG = 0x35,
    IPP_TAG_NAMELANG = 0x36,
    IPP_TAG_TEXT = 0x41,
    IPP_TAG_NAME = 0x42,
    IPP_TAG_KEYWORD = 0x44,
    IPP_TAG_URI = 0x45,
    IPP_TAG_URISCHEME = 0x46,
    IPP_TAG_CHARSET = 0x47,
    IPP_TAG_LANGUAGE = 0x48,
    IPP_TAG_MIMETYPE = 0x49,
    IPP_TAG_MEMBERNAME = 0x4A,
    IPP_TAG_MEMBERATTR = 0x4B,
    IPP_TAG_EXTENSION = 0x7F
} ipp_tag_t;

typedef enum {
    CUPS_FORMAT_AUTO,
    CUPS_FORMAT_PDF,
    CUPS_FORMAT_POSTSCRIPT,
    CUPS_FORMAT_RAW,
    CUPS_FORMAT_JPEG,
    CUPS_FORMAT_PNG,
    CUPS_FORMAT_RENDER
} cups_format_t;

# ifdef __cplusplus
}
# endif

#endif /* _CUPS_CUPS_H_ */
